### PR TITLE
Improved icons

### PR DESCRIPTION
**Pull request by rderimay**
This is a PR to improve my first set of icons to make them more readable on the images as they were before.
No fonctionnality change, just better icons.

### CODE REVIEW

**Comment by musselwhizzle** [comment]
1757 assets :O. Ya killing me. Can you give a summary and perhaps provide before and after screenshots of what changed.

**Comment by rderimay** [comment]
I was sure you would love it. Before and After,  this is subtle but make quite a big difference when displayed over photos :
capture 2017-01-11 a 08 49 00

**Comment by musselwhizzle** [comment]
looks good. should this be merged AFTER the other PR?

**Comment by rderimay** [comment]
Yes

**Comment by rderimay** [comment]
No, sorry, in fact it can be merged immediately. Fully compatible. I will definitely appreciate you to merge directly to master, because I can see the position of the icons for testing better definitely.

**Comment by musselwhizzle** [comment]
i will put this in the same branch as the other PR. are you familiar enough with branch that you are comfortable switching between them?

**Comment by musselwhizzle** [comment]
oh, i see. Ok. will merge away now.

**Pull request merged**
