### PR TITLE
Windows and canon 80d support

### PR DESCRIPTION
**Pull request by jandhollander**
Added windows support for exiftool:
- paths with spaces are handled correctly in the exiftool command (might break OS X support, maybe there's a toggle necessary based on environment)
- working exe for exiftool added to bin folder

Added Canon 80D support:
- Correct metadata tag "Focus Points In Focus" is used to find the focus points in the photo metadata
- Focus point mapping is added based on data from metadata found in exiftool. This may need some tweaking.

Remaining issues I see:
- MetadataDialog shows no data even though the metadata file from exiftool is written and read correctly
- FocusPointDialog shows picture but not the focus point that should be shown, even though the coordinates appear to be correct (at first sight). Maybe a problem with loading the image asset on windows?

### CODE REVIEW

**Comment by musselwhizzle** [comment]
Thanks! I'll make sure things still work for iOS and then merge it into master.

**Comment by musselwhizzle** [comment]
btw, if you want to show up as a "contributor" to this repo, make a insignifcant change and PR into master. Github doesn't give contributions when I PR into a non-master branch.

**Comment by musselwhizzle** [comment]
Wait, so focus viewer dialog isn't showing any focus points? Can you try with one of my images? That's kind of big deal...ya know. 

https://github.com/musselwhizzle/Focus-Points-Sample-Images

**Comment by jandhollander** [comment]
I didn't have any supported images other than my 80D, so yeah, I didn't test.

I'll try some sample images tomorrow ;)

**Comment by jandhollander** [comment]
Sample images don't show focus points either...

**Pull request merged**
