### PR TITLE
Fuji bugfix

### PR DESCRIPTION
**Pull request by rderimay**
This solves 2 problems of the current master:
- Works on rafs
- Works on vertical images

### CODE REVIEW

**Comment by musselwhizzle** [comment]
Thank you. I assume you have a Fuji camera. Would you be willing to help out more? I mapped everything from the top, left of the image to the top left of the focus box on my camera. I would assume Fuji gives the center point of the focus box and not the top left. As such, the focus box will be off by it's dimensions-scaled. Would you be interested in helping and confirming there?

**Comment by rderimay** [comment]
Yes I own a few in fact (x-t1, x-t2, x30).
Yes no problem, I am happy to help. In fact I spent most of the time trying to find out how to add my changes to the git :-) 
I can also help on other themes should you need capacity. My knowledge on .lua is very limited but it seems to be pretty straight forward.

I understand that your AFpoint is not the center of the focus box but the top left. This explains why I had some deviations.
What do you think ? Isn't it better to change your code to make it the middle of the box for all cameras ? This would require to change the few configuration files that already exist but I feel it to be more future proof to do it now.
Alternatively we could change the Fujidelegate to handle it but I am the opinion this is crap.
For example, the Fuji cameras (I assume many hybrids) can change the size of the focus points (very small, small, normal, big) I already searched for an exif field that could lead top the size but did not find it. I am pretty confident this exists in the exif and I will find it later.
For this reason, it seems more logical to center everything ?

**Comment by musselwhizzle** [comment]
I'm leaning towards yes i makes sense to change everything to center point. But it's time to go to work, so let me think about it a little later on. I appreciate the help thus far.

**Comment by rderimay** [comment]
ok let me know what you decided and on what you'd like me to help

**Comment by musselwhizzle** [comment]
How about this: 
* Let's modify "DefaultDelegate.getDefaultAfPoints" to return the center points adjusting for it in code by adding 1/2 focusPointDimens to the return values.
* Modify the default renderer to position the focus box based upon x,y being center. 

If you're for the task, make a branch and give it a wack. If not, I can take it on.

**Comment by rderimay** [comment]
ok, i'll do it

**Comment by rderimay** [comment]
and what about changing the 3 existing focus_points files at the same time ? That way we have something consistent from the center

**Comment by musselwhizzle** [comment]
Let's leave those for now because I have a couple other people currently in the process of making some maps. If we go the route of having those centered, I'll just update them then remove the offset in the code.

**Comment by rderimay** [comment]
Looking at the code, I am right if I say that right now, the focus box does not comply to the focusDimensions ?

**Comment by musselwhizzle** [comment]
correct. Unfortunately, lightroom does not allow me to dynamically resize the red focus box UI. So it's just an estimate (a really good one for my camera without a big crop)

**Comment by rderimay** [comment]
Done. Hope this is fine. 
Maybe we could add a folder with test images to be able to test the plugin for camera we don't own.
There is a bug in the calculation of the position of the focus points when a angled crop has been used. I did not fix it.

**Comment by musselwhizzle** [comment]
test images: https://github.com/musselwhizzle/Focus-Points-Sample-Images

**Comment by musselwhizzle** [comment]
RE: There is a bug in the calculation of the position of the focus points when a angled crop has been used. I did not fix it.

Yes, a gentleman is working on that and has a PR out for it right now. He got it close, but not exact.

**Comment by rderimay** [comment]
Excellent

**Comment by rderimay** [comment]
Can it be that it did not get it exact because the old algorithm was using the left top corner instead of the center ??

**Comment by musselwhizzle** [comment]
Nah, I dont think so. I tried many things and basically I'm sure I was just off. I THINK what it is is, the images rotates in the middle. so x,y focus point follows a path of a circle around the middle point of the image by "a" radius. There's then an offset for whatever is considered top-left now. Check out the PR that's opened right now if you want. Or feel free to play around with your own version too

**Comment by rderimay** [comment]
Yeah ok. I integrated the PR#10 in my version and it is not working correctly even if it seems to be better. You can manage to get the point far away pretty easily.

**Comment by rderimay** [comment]
2 questions:
- Is there a way to let LR understand it should reload the plugin on every change ? Unloading/Loading is tiring and loose time. And sometimes it still does not reload it and you need to restart LR completely.
- When you write log() in the code, where is it logged ?

**Comment by musselwhizzle** [comment]
1. see screen shot

screen shot 2017-01-04 at 2 24 08 pm


for logging: I do this: tail -f ~/Documents/libraryLogger.log

in Utils.lua turn on isLog = true but dont check that in to "production" code.

**Comment by musselwhizzle** [comment]
if you add new files, yes you probably need to restart LR. Modifying, it should pick up the changes.

**Comment by rderimay** [comment]
perfect, thanks

**Comment by rderimay** [comment]
Can you confirm that the CropLeft Right Top Bottom values are the values of the top left and the bottom right corners ?
Can not find a description on this in the docs.

capture 2017-01-05 a 00 08 50

**Comment by musselwhizzle** [comment]
i read that as 0% off the left side 10% from the top. right size is at 92% percent away from the left edge and same for the bottom. All of the math worked out dead on for me for any crop minus rotation so that understanding should be right.

**Comment by rderimay** [comment]
yes of course, but from the top left corner and from the bottom right corner thats the point. I verified that.
ok ill try to work on this tomorrow.

**Pull request merged**
