### PR TITLE
Musselwhizzle/master

### PR DESCRIPTION
**Pull request by rderimay**

### CODE REVIEW

**Comment by musselwhizzle** [comment]
Will move it to a feature branch for now.

**Comment by musselwhizzle** [comment]
Whenever possible, please have the PRs be focused on 1 specific thing. As it stands, I will pick and pull some code from this, but not accept the PR.

**Comment by musselwhizzle** [comment]
Heads up if you want to tackle this: 
https://github.com/musselwhizzle/Focus-Points/issues/48

**Comment by rderimay** [comment]
I understand, that some PR are difficult to merge but I concentrated on 1 specific thing : making it work on Windows. Doing that a lot of small stuff needed to be done to make sense. The only things which were not related to that is the renaming of FocusPoint in ShowFocusPoint and the refactoring around the one dialog to be more consistent with the other one.

**Comment by musselwhizzle** [comment]
moved into feature branch.

**Pull request merged**
