### PR TITLE
Fix math bug in rotated images (Olympus Cameras)

### PR DESCRIPTION
**Pull request by mkjanke**

### CODE REVIEW

**Comment by musselwhizzle** [comment]
whenever possible, separate out completely independent features into different PRs. It would be nice to have the Panasonic in a feature branch for a bit while still being able to take in these bug fixes. If you're good enough with git, can you make those changes?

**Comment by mkjanke** [comment]
That was my intent. 

Unfortunately I'm new at this, having last performed fork/pull/merge using punch cards in 1980. It was simpler then. ;)

**Comment by musselwhizzle** [comment]
no worries. If it's too much, I can take care of it. Whatever you feel comfortable with fine and I'll take it from there.

**Comment by mkjanke** [comment]
Help would be appreciated. 

Can you clean it up by separating the Olympus bug fix from the Panasonic feature?

**Comment by musselwhizzle** [comment]
Yea, I'll take care of it tomorrow sometime. Appreciate the help on the project. Hope you're having fun with it. :)

**Pull request merged**
