### PR TITLE
Added Canon EOS 40D

### PR DESCRIPTION
**Pull request by profesorek96**
Please add to main repository.

### CODE REVIEW

**Comment by rderimay** [comment]
I am pretty sure this is unneeded as -unless we have a bug- the current version supports the 40D (and almost any Canon camera) without config file.

**Comment by musselwhizzle** [comment]
do most canon's report their x and y pixel locations just like fuji? I'm feeling very left out that nikon didn't.

**Comment by rderimay** [comment]
Indeed yes, I was pretty socked to find no infos at all in the Nikon files I have opened. This is crazy simple to implement for them I cannot understand why they did not.
The same as Fuji that implemented a lot of stuff in the Exif (af positions, face recognition squares, etc) but did NOT implement the current chosen size if the af point...

**Comment by musselwhizzle** [comment]
before I merge or decline, l or you can grab his images out of the image repo and test that the current version works there.

**Comment by rderimay** [comment]
40 D Output:

`EXIF | Searching for AF Area Widths -> 97 97 97 97 97 97 97 97 97
EXIF | Searching for AF Area Heights -> 98 98 98 98 98 98 98 98 98
EXIF | Searching for AF Area X Positions -> 0 -649 649 -1034 0 1034 -649 649 0
EXIF | Searching for AF Area Y Positions -> 562 298 298 0 0 0 -298 -298 -562
EXIF | Searching for AF Points Selected -> 4
EXIF | Searching for { AF Points In Focus } returned nothing
`

**Comment by rderimay** [comment]
does he just put some ?

**Comment by musselwhizzle** [comment]
yes

https://github.com/musselwhizzle/Focus-Points-Sample-Images/tree/master/Canon/EOS%2040D

**Comment by rderimay** [comment]
ah ok. second

**Comment by rderimay** [comment]
Works

**Comment by rderimay** [comment]
capture 2017-01-10 a 23 10 26

**Comment by rderimay** [comment]
And with rotated, cropped and mirrored ^_^

capture 2017-01-10 a 23 10 55

**Comment by musselwhizzle** [comment]
to confirm: is it your recommendation to decline this PR.

**Comment by rderimay** [comment]
yes

**Comment by musselwhizzle** [comment]
decline PR as camera support already exists dynamically. 

@profesorek96 - if you find this to be untrue, let's reopen and investigate at that time.

**Pull request closed without merging**
