### PR TITLE
Support of new camera maker OMDS (OM-1, OM-5) plus some fixes

### PR DESCRIPTION
**Pull request by capricorn8**
Handles issues #144, #162, #164, #168, #169

Requires incorporation of updated exiftool (minimum version 12.60, which is not included in this pull request)

### CODE REVIEW

**Comment by capricorn8** [comment]
Hope I got this right, as someone who is not familiar with GitHub.

Can you please only merge the five LUA files?
I failed to upload the entire structure under focuspoints.lrdevplugin\bin\exiftool so please ignore commits 6, 7.

Also, can you please update exiftool to the latest version (12.69 at this time), or minimum 12.60 if you only want "production release" to be part of the plugin.

**Comment by capricorn8** [comment]
Hope I got this right, as someone who is not familiar with Github.

Can you please merge the five LUA files only.
I failed to upload the entire structure under focuspoints.lrdevplugin\bin\exiftool so please ignore commits 6, 7.

Also, can you please update exiftool to the latest version (12.69 at this time), or minimum 12.60 if you only want "production release" to be part of the plugin.

**Comment by capricorn8** [comment]
I guess I shouldn't have closed this with nothing being merged in main ...

**Comment by musselwhizzle** [comment]
i merged it now. thank you!

**Pull request merged**
