### PR TITLE
remove LR preference mogrifyUsage

### PR DESCRIPTION
**Pull request by ropma**
With the removal of the options section, there isn't any UI to the set or unset the LR preference parameter mogrifyUsage. Thus the usage of the parameter is removed. 

I don't know if this fix also solves the load problem of MogrifyUtils on a Mac.

### CODE REVIEW

**Comment by musselwhizzle** [comment]
I'll need about 4 days before I can test it out

**Comment by ropma** [comment]
No problem - thanks. 

The second commit fixes the rendering problem with flipped images reported in PR #143. And also contains some minor code improvements (missing keyword 'local' for local variables)

**Comment by musselwhizzle** [comment]
Screen Shot 2019-10-07 at 4 26 13 PM

This is what shows up immediately when I try to open it on mac. I can't figure out where it's coming from

**Comment by musselwhizzle** [comment]
Gezz. I forgot you have to go and manually reload the plugin anytime a new class is added. That fixed it. I'm finally able to QA now.

**Comment by musselwhizzle** [comment]
Usually uninstalling the plugin and reinstalling it fixes it whenever a new class file is added, but that's not doing the trick here for me.

**Comment by ropma** [comment]
MogrifyUtils essentially creates a command line, which is then executed using LrTask.execute (similar to ExifUtils). There are no direct dependencies to the ImageMagick/Mogirfy installation.  I used a LUA 5.1 compiler to check the syntax  during development . I don't understand why there a loading problem on a Mac.
I will ask a friend if I can do a test on his Macbook...

**Comment by musselwhizzle** [comment]
Hopefully i can work on it this weekend too

**Comment by musselwhizzle** [comment]
I deleted everything I had locally and then reinstalled it fresh and it worked. Must had been something weird on my part. Looks great. I'm going to merge this over into master now. Nice job!

**Pull request merged**
